// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.6.1
// source: codec.proto

package codec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SemanticSeries 消息
type SemanticSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesSegment string                 `protobuf:"bytes,1,opt,name=series_segment,json=seriesSegment,proto3" json:"series_segment,omitempty"` // 系列段
	SegmentLen    int64                  `protobuf:"varint,2,opt,name=segment_len,json=segmentLen,proto3" json:"segment_len,omitempty"`         // 段长度
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                                      // 值（字节数组）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSeries) Reset() {
	*x = SemanticSeries{}
	mi := &file_codec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSeries) ProtoMessage() {}

func (x *SemanticSeries) ProtoReflect() protoreflect.Message {
	mi := &file_codec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSeries.ProtoReflect.Descriptor instead.
func (*SemanticSeries) Descriptor() ([]byte, []int) {
	return file_codec_proto_rawDescGZIP(), []int{0}
}

func (x *SemanticSeries) GetSeriesSegment() string {
	if x != nil {
		return x.SeriesSegment
	}
	return ""
}

func (x *SemanticSeries) GetSegmentLen() int64 {
	if x != nil {
		return x.SegmentLen
	}
	return 0
}

func (x *SemanticSeries) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// SemanticMeta 消息
type SemanticMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetaSegment   string                 `protobuf:"bytes,1,opt,name=meta_segment,json=metaSegment,proto3" json:"meta_segment,omitempty"` // 元数据段
	SegmentLen    int64                  `protobuf:"varint,2,opt,name=segment_len,json=segmentLen,proto3" json:"segment_len,omitempty"`   // 段长度
	SeriesNum     int64                  `protobuf:"varint,3,opt,name=series_num,json=seriesNum,proto3" json:"series_num,omitempty"`      // 系列数量
	SeriesArr     []*SemanticSeries      `protobuf:"bytes,4,rep,name=series_arr,json=seriesArr,proto3" json:"series_arr,omitempty"`       // 系列数组
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticMeta) Reset() {
	*x = SemanticMeta{}
	mi := &file_codec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticMeta) ProtoMessage() {}

func (x *SemanticMeta) ProtoReflect() protoreflect.Message {
	mi := &file_codec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticMeta.ProtoReflect.Descriptor instead.
func (*SemanticMeta) Descriptor() ([]byte, []int) {
	return file_codec_proto_rawDescGZIP(), []int{1}
}

func (x *SemanticMeta) GetMetaSegment() string {
	if x != nil {
		return x.MetaSegment
	}
	return ""
}

func (x *SemanticMeta) GetSegmentLen() int64 {
	if x != nil {
		return x.SegmentLen
	}
	return 0
}

func (x *SemanticMeta) GetSeriesNum() int64 {
	if x != nil {
		return x.SeriesNum
	}
	return 0
}

func (x *SemanticMeta) GetSeriesArr() []*SemanticSeries {
	if x != nil {
		return x.SeriesArr
	}
	return nil
}

var File_codec_proto protoreflect.FileDescriptor

var file_codec_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x6f, 0x64, 0x65, 0x63, 0x22, 0x6e, 0x0a, 0x0e, 0x53, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63,
	0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73,
	0x5f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0xa7, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69,
	0x63, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x74,
	0x61, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x65, 0x72, 0x69, 0x65, 0x73, 0x4e, 0x75, 0x6d, 0x12, 0x34, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x69,
	0x65, 0x73, 0x5f, 0x61, 0x72, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63,
	0x6f, 0x64, 0x65, 0x63, 0x2e, 0x53, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x53, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x52, 0x09, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x41, 0x72, 0x72, 0x42, 0x0d,
	0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x3b, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_codec_proto_rawDescOnce sync.Once
	file_codec_proto_rawDescData []byte
)

func file_codec_proto_rawDescGZIP() []byte {
	file_codec_proto_rawDescOnce.Do(func() {
		file_codec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codec_proto_rawDesc), len(file_codec_proto_rawDesc)))
	})
	return file_codec_proto_rawDescData
}

var file_codec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_codec_proto_goTypes = []any{
	(*SemanticSeries)(nil), // 0: codec.SemanticSeries
	(*SemanticMeta)(nil),   // 1: codec.SemanticMeta
}
var file_codec_proto_depIdxs = []int32{
	0, // 0: codec.SemanticMeta.series_arr:type_name -> codec.SemanticSeries
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_codec_proto_init() }
func file_codec_proto_init() {
	if File_codec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codec_proto_rawDesc), len(file_codec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codec_proto_goTypes,
		DependencyIndexes: file_codec_proto_depIdxs,
		MessageInfos:      file_codec_proto_msgTypes,
	}.Build()
	File_codec_proto = out.File
	file_codec_proto_goTypes = nil
	file_codec_proto_depIdxs = nil
}
